name: Package Release
on:
  push:
    branches:
      - main
jobs:
  release:
    uses: rainlanguage/rainix/.github/workflows/rainix-autopublish.yaml@main
    with:
      soldeer-package: rain-datacontract
    secrets: inherit
